'use strict';
const D=StarkswayData,E=StarkswayEngine,$=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=(now=new Date())=>E.phToday(now,D.config.timezone);
const fmt=v=>E.date(v)?new Intl.DateTimeFormat('en-PH',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(E.date(v)):'Choose date';
const initial=()=>{const start=today(),eta=E.etaWindow(start,new Date(),D.config);return {step:0,checkIn:start,checkOut:E.addDay(start),adults:2,childAges:[],pets:false,items:[],guest:{eta:eta.value},requests:{},agreed:false,method:'gcash',proof:null,paymentStatus:'awaiting_dp',bookingStatus:'draft',paymentHistory:['awaiting_dp'],bookingHistory:['draft'],reference:null,loading:false,busy:false,demoConflict:false}};
const reservationLocked=()=>state.paymentStatus!=='awaiting_dp'||state.bookingStatus!=='draft';
function resetPaymentForChange(){state.proof=null;state.paymentStatus='awaiting_dp';state.bookingStatus='draft';state.paymentHistory=['awaiting_dp'];state.bookingHistory=['draft'];state.reference=null;state.busy=false;state.agreed=false;}
let state=initial(),gallery={room:null,index:0};
const steps=['Dates','Stays','Cart','Details','Add-ons','Review','Payment','Status'];
const button=(label,action,kind='')=>`<button class="button ${kind}" type="button" data-action="${action}">${label}</button>`;
const heading=(n,title,text)=>`<p class="eyebrow">${n}</p><h1>${title}</h1><p class="lede">${text}</p><div id="errors" role="alert"></div>`;
const field=(label,name,value,type='text',attrs='')=>`<label>${label}<input type="${type}" name="${name}" value="${esc(value)}" ${attrs}></label>`;
const toast=message=>{const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2600)};
const rules=()=>`<div class="notice strong"><strong>STARKSWAY IS A SWIMMING POOL RESORT ONLY — NO BEACH.</strong></div><div class="rule-grid">${D.rules.slice(1).map((r,i)=>`<div class="rule"><strong>${r}</strong>${i===0?'<small>Standard check-in 2:00 PM · check-out 12:00 NN</small>':''}</div>`).join('')}</div>`;
const policies=()=>D.policies.map(([a,b])=>`<h3>${a}</h3><p>${b}</p>`).join('');
function errors(list){const el=$('#errors');if(el){el.innerHTML=`<div class="error">${list.map(esc).join('<br>')}</div>`;el.scrollIntoView({block:'center'})}}
function setStep(step){if(reservationLocked()&&step<7){toast('Reservation details are locked after payment proof submission. Start a new review to make changes.');return}captureDraft();state.step=step;state.loading=step===1;if($('#dialog').open)$('#dialog').close();render();if(step===1)queueMicrotask(()=>{state.loading=false;render()});window.scrollTo({top:0});$('#main').focus()}
function roomFor(item){return item.kind==='exclusive'?D.exclusive:D.rooms.find(r=>r.id===item.resourceId)}
function item(id,kind='room'){return {id:`item-${id}`,kind,resourceId:id,adults:state.items.length?0:state.adults,childIndexes:state.items.length?[]:state.childAges.map((_,i)=>i),childAges:state.items.length?[]:[...state.childAges]}}
function allocation(){return E.allocation(state,D)}
function allocationMarkup(){const a=allocation(),adultOver=a.adultsLeft<0,childOver=a.childrenLeft<0;return `<section id="allocationStatus" class="allocation-status ${a.allAssigned?'complete':adultOver||childOver||a.duplicateChildIndexes.length||a.capacityErrors.length?'invalid':''}" aria-live="polite"><p class="eyebrow">${a.allAssigned?'Allocation complete':'Guests left to assign'}</p>${a.allAssigned?'<h2>✓ All guests assigned</h2>':`<div class="allocation-counts"><strong>${Math.max(0,a.adultsLeft)} adult${Math.abs(a.adultsLeft)===1?'':'s'}</strong><strong>${Math.max(0,a.childrenLeft)} child${Math.abs(a.childrenLeft)===1?'':'ren'}</strong></div>`}${adultOver?`<p>You have assigned ${a.assignedAdults} adults, but this reservation contains ${state.adults}.</p>`:''}${childOver||a.duplicateChildIndexes.length?'<p>Each child can be assigned to exactly one accommodation.</p>':''}${a.capacityErrors.map(x=>`<p>${esc(x)}</p>`).join('')}</section>`}
function render(){
 $('#progress').innerHTML=steps.map((s,i)=>`<button type="button" data-step="${i}" class="${i<state.step?'done':''}" ${i>state.step?'disabled':''} ${i===state.step?'aria-current="step"':''}><span>${i+1}</span>${s}</button>`).join('');
 $('#content').innerHTML=[datesView,staysView,cartView,detailsView,addonsView,reviewView,paymentView,statusView][state.step]();
 summaryView();wireDynamic();
}
function datesView(){return heading('01 / Plan your escape','A simple way to stay.','Choose one shared date range, then combine one or more Starksway accommodations in a single reservation.')+`<form id="datesForm" class="panel"><div class="form-grid">${field('Check-in · 2:00 PM','checkIn',state.checkIn,'date',`required min="${today()}"`)}${field('Check-out · 12:00 NN','checkOut',state.checkOut,'date',`required min="${E.addDay(state.checkIn)}"`)}${field('Adults','adults',state.adults,'number','required min="1" max="100"')}${field('Children','children',state.childAges.length,'number','required min="0" max="30"')}<div id="childAges" class="wide form-grid">${childAgeFields()}</div></div><label class="check"><input name="pets" type="checkbox" ${state.pets?'checked':''}><span>Bringing a pet <small>· ₱1,000 refundable security deposit upon check-in</small></span></label><div class="notice">Consecutive nights are supported. Friday, Saturday and configured Philippine national holidays use the special rate; Sunday uses the regular rate unless it is a configured holiday. Same-day booking is supported until 11:59 PM and does not extend checkout.</div><div class="actions"><button class="button accent">Check availability →</button></div></form>${rules()}`}
function childAgeFields(){return state.childAges.map((v,i)=>field(`Child ${i+1} age`,`age-${i}`,v,'number','required min="0" max="17" placeholder="Select age"')).join('')}
function availability(product){return product.id===D.exclusive.id?E.exclusiveAvailable(state.checkIn,state.checkOut,D):E.roomAvailable(product.id,state.checkIn,state.checkOut,D)}
function earliestAvailableCheckIn(product){const first=availability(product);if(first.available||!first.conflict?.checkOut)return null;const stayNights=Math.max(1,E.nights(state.checkIn,state.checkOut));let candidate=first.conflict.checkOut;for(let i=0;i<120;i++){const out=E.addDay(candidate,stayNights);const next=product.id===D.exclusive.id?E.exclusiveAvailable(candidate,out,D):E.roomAvailable(product.id,candidate,out,D);if(next.available)return candidate;if(!next.conflict?.checkOut||next.conflict.checkOut<=candidate)return candidate;candidate=next.conflict.checkOut}return candidate}
function availabilityExplanation(product,a=availability(product)){if(a.available)return '';const next=earliestAvailableCheckIn(product);if(!next)return `<div class="availability-explain"><strong>Unavailable for the selected dates.</strong><span>Choose different dates to continue.</span></div>`;return `<div class="availability-explain"><strong>Already booked until ${fmt(next)}, 12:00 NN.</strong><span>Earliest available check-in: ${fmt(next)}, 2:00 PM.</span></div>`}
