'use strict';
function staysView(){
 const inCart=id=>state.items.some(i=>i.resourceId===id),hasExclusive=inCart(D.exclusive.id),hasRooms=state.items.some(i=>i.kind==='room');
 if(state.loading)return heading('02 / Available stays','Finding your Starksway stay…','Checking every independent accommodation against the selected dates.')+`<div class="room-grid"><div class="skeleton skeleton-card"></div><div class="skeleton skeleton-card"></div><div class="skeleton skeleton-card"></div><div class="skeleton skeleton-card"></div></div>`;
 const exclusiveAvailability=availability(D.exclusive);
 return heading('02 / Choose your stay','Space to be together.','Add several individual accommodations, or reserve the entire resort as one exclusive booking product.')+
 `<div class="notice availability-disclosure">Review availability includes the colored September–November bookings supplied by Starksway plus written corrections. Final live availability will still be synchronized with the Admin Dashboard and backend before launch.</div><div class="notice">Pending payment does not hold inventory. Final availability is rechecked after payment proof is submitted.</div>
 <div class="catalog-head"><div><h2>${fmt(state.checkIn)} → ${fmt(state.checkOut)}</h2><p>${E.nights(state.checkIn,state.checkOut)} night(s) · nine independent one-unit accommodations</p></div>${button('Edit dates','dates')}</div>
 <article class="exclusive-card"><img src="${D.exclusive.images[0]}" alt="Starksway pools at night"><div class="exclusive-copy"><p class="eyebrow">Private whole-resort stay</p><h2>${D.exclusive.name}</h2><p>All nine sleeping accommodations plus the Function Hall. Base sleeping capacity 57 guests; excess guests are allowed at ₱300 per person.</p><div class="chips">${D.exclusive.features.map(x=>`<span class="chip">${x}</span>`).join('')}</div><div class="rate">${E.money(D.exclusive.regular)}<small>per night · 50% down payment</small></div><span class="badge ${exclusiveAvailability.available?'':'pending'}">${exclusiveAvailability.available?'Available in review schedule':'Unavailable for these dates'}</span><div class="actions"><button class="button accent" data-add-exclusive ${inCart(D.exclusive.id)||hasRooms||!exclusiveAvailability.available?'disabled':''}>${inCart(D.exclusive.id)?'Added to booking':hasRooms?'Remove room stays to select':'Reserve entire resort'}</button></div></div></article>
 <div class="catalog-head"><div><h2>Individual accommodations</h2><p>Each name below is one independent physical unit.</p></div><button class="button primary" data-action="cart" ${state.items.length?'':'disabled'}>Booking cart · ${state.items.length}</button></div>
 <div class="room-grid">${D.rooms.map(r=>roomCard(r,inCart(r.id),hasExclusive)).join('')}</div>
 ${state.items.length?`<div class="results-continue"><div><strong>${state.items.length} ${state.items.length===1?'stay':'stays'} selected</strong><small>Review guest allocation and totals next.</small></div><button class="button accent" data-action="cart">Continue to booking cart · ${state.items.length} ${state.items.length===1?'stay':'stays'} →</button></div>`:''}`;
}
function roomCard(r,added,hasExclusive){const a=availability(r),first=E.rate(r,state.checkIn,D.config);return `<article class="room-card"><img src="${r.cover||r.images[0]}" loading="lazy" alt="${r.name} accommodation"><div class="room-body"><div><span class="badge ${a.available?'':'pending'}">${a.available?'Available in review schedule':'Unavailable for these dates'}</span></div>${availabilityExplanation(r,a)}<p class="eyebrow">${r.type}</p><h2>${r.name}</h2><p>Base capacity ${r.baseCapacity} · up to ${r.maxCapacity} with excess guests</p><div class="chips">${r.features.slice(0,3).map(x=>`<span class="chip">${x}</span>`).join('')}</div><div class="rate">${E.money(first.amount)}<small>${first.label} · first-night rate; multi-night totals are calculated night by night.</small></div><div class="actions"><button class="button primary" data-add="${r.id}" ${added||hasExclusive||!a.available?'disabled':''}>${added?'Added':hasExclusive?'Exclusive stay selected':a.available?'Add to booking':'Unavailable'}</button><button class="button" data-detail="${r.id}">View details</button></div></div></article>`}
function cartView(){if(!state.items.length)return heading('03 / Booking cart','Your booking is empty.','Choose one or more stays to continue.')+`<div class="empty"><h2>Let’s find your stay.</h2><div class="actions">${button('Browse accommodations','stays','accent')}</div></div>`;
 const q=E.quote(state,D),a=allocation();return heading('03 / Booking cart','One booking. Every stay.','Distribute the reservation total across the selected stays. A paid stay may remain reserved with zero assigned guests.')+`<form id="cartForm">${allocationMarkup()}${state.childAges.length?`<section class="panel child-assignment"><h2>Assign each child once</h2><p>Every child keeps the age entered on the Dates step. Age 2+ counts toward room occupancy.</p><div class="form-grid">${state.childAges.map((age,c)=>{const selected=state.items.findIndex(i=>i.childIndexes.includes(c));return `<label>Child ${c+1} · age ${age}<select name="child-room-${c}"><option value="">Needs accommodation</option>${state.items.map((i,n)=>`<option value="${n}" ${selected===n?'selected':''}>${roomFor(i).name}</option>`).join('')}</select></label>`}).join('')}</div></section>`:''}${q.items.map((i,n)=>cartItem(i,n)).join('')}<div class="actions">${button(iExclusive()?'Change selection':'Add another accommodation','stays') }<button class="button accent" id="cartContinue" ${a.allAssigned?'':'disabled'}>Continue to guest details →</button></div></form>`}
function cartItem(i,n){const assignedChildren=i.childIndexes.map(c=>`Child ${c+1} · age ${state.childAges[c]}`).join(', ');const maxAttr=i.room.maxCapacity!=null?`max="${i.room.maxCapacity}"`:'';return `<article class="cart-item"><div class="cart-top"><img src="${i.room.images[0]}" alt=""><div><p class="eyebrow">${i.room.type}</p><h2>${i.room.name}</h2><div class="cart-meta">${fmt(state.checkIn)} → ${fmt(state.checkOut)} · ${E.nights(state.checkIn,state.checkOut)} night(s)</div></div><button class="text-button" type="button" data-remove="${n}">Remove</button></div><div class="allocation">${field('Adults in this stay',`adults-${n}`,i.adults,'number',`required min="0" ${maxAttr}`)}<div><strong>${i.childIndexes.length} ${i.childIndexes.length===1?'child':'children'} assigned</strong><div class="small muted">${assignedChildren||'No children assigned to this stay.'}</div></div><div><strong>Base capacity ${i.room.baseCapacity}</strong><div class="small muted">${i.room.maxCapacity?`Maximum ${i.room.maxCapacity}`:'Absolute maximum pending client confirmation'} · ₱300 per excess guest age 2+</div></div></div>${i.excess?`<div class="excess-charge"><div><span>Excess guest charge</span><strong>${i.excess} × ${E.money(D.config.extraGuestPrice)} = ${E.money(i.excessKnownAmount)}</strong></div><small>Collection timing and multi-night treatment to be confirmed. This amount is not included in the accommodation subtotal or 50% down payment.</small></div>`:''}<div class="moneyline"><span>Accommodation subtotal</span><strong>${E.money(i.roomSubtotal)}</strong></div><div class="small muted">${i.lines.map(l=>`${fmt(l.day)} · ${l.label} ${E.money(l.amount)}`).join('<br>')}</div></article>`}
function iExclusive(){return state.items.some(i=>i.kind==='exclusive')}
function detailsView(){const g=state.guest,eta=E.etaWindow(state.checkIn,new Date(),D.config),etaValue=g.eta||eta.value;return heading('04 / Guest details','Who should we welcome?','One main contact manages the entire multi-accommodation reservation.')+`<form id="guestForm" class="panel"><div class="form-grid">${field('First name','firstName',g.firstName||'','text','required maxlength="80" autocomplete="given-name"')}${field('Last name','lastName',g.lastName||'','text','required maxlength="80" autocomplete="family-name"')}${field('Email','email',g.email||'','email','required maxlength="150" autocomplete="email"')}${field('Philippine mobile','mobile',g.mobile||'','tel','required placeholder="09XX XXX XXXX" autocomplete="tel"')}<label>Estimated arrival time<input name="eta" type="time" min="${eta.min}" value="${esc(etaValue)}" required><small>${eta.sameDayLate?`Same-day booking: choose an arrival time at or after ${eta.min} PH time. Checkout remains 12:00 NN tomorrow.`:'Check-in begins at 2:00 PM PH time.'}</small></label><label class="wide">Address<input name="address" required maxlength="250" autocomplete="street-address" value="${esc(g.address||'')}"></label><label class="wide">Special requests · optional<textarea name="special" maxlength="1000">${esc(g.special||'')}</textarea></label></div><div class="notice">${state.adults} adult(s) · ${state.childAges.length} child(ren) · Pet: ${state.pets?'Yes':'No'}. Only necessary reservation details are collected.</div><div class="actions">${button('Back to cart','cart')}<button class="button accent">Continue to add-ons →</button></div></form>`}
