'use strict';
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.step!=null&&!b.disabled)return setStep(Number(b.dataset.step));
 if(b.dataset.action){const go={dates:0,stays:1,cart:2,details:3,addons:4,review:5,payment:6};if(b.dataset.action in go)return setStep(go[b.dataset.action]);if(b.dataset.action==='modal-cart')return setStep(2);if(b.dataset.action==='modal-close')return $('#dialog').close();if(b.dataset.action==='policies'){ $('#dialogBody').innerHTML=`<h2 id="dialogTitle">Booking policies</h2>${policies()}`;return $('#dialog').showModal()}if(b.dataset.action==='reset'){state=initial();return setStep(0)}if(b.dataset.action==='demo-confirm'){if(state.busy)return;state.busy=true;b.disabled=true;b.textContent='Rechecking availability…';return queueMicrotask(()=>{const unavailable=state.items.some(i=>i.kind==='exclusive'?!E.exclusiveAvailable(state.checkIn,state.checkOut,D).available:!E.roomAvailable(i.resourceId,state.checkIn,state.checkOut,D).available);if(unavailable){state.paymentStatus=E.transition(E.paymentTransitions,state.paymentStatus,'availability_conflict');state.paymentHistory.push(state.paymentStatus);state.bookingStatus=E.transition(E.bookingTransitions,state.bookingStatus,'availability_conflict');state.bookingHistory.push(state.bookingStatus)}else{state.paymentStatus=E.transition(E.paymentTransitions,state.paymentStatus,'payment_verified');state.paymentHistory.push(state.paymentStatus);state.bookingStatus=E.transition(E.bookingTransitions,state.bookingStatus,'confirmed');state.bookingHistory.push(state.bookingStatus)}state.busy=false;render()})}if(b.dataset.action==='demo-conflict'){state.paymentStatus=E.transition(E.paymentTransitions,state.paymentStatus,'availability_conflict');state.paymentHistory.push(state.paymentStatus);state.bookingStatus=E.transition(E.bookingTransitions,state.bookingStatus,'availability_conflict');state.bookingHistory.push(state.bookingStatus);return render()}if(b.dataset.action==='demo-refund'){state.paymentStatus=E.transition(E.paymentTransitions,state.paymentStatus,'refund_required');state.paymentHistory.push(state.paymentStatus);state.bookingStatus=E.transition(E.bookingTransitions,state.bookingStatus,'refund_required');state.bookingHistory.push(state.bookingStatus);toast('Refund-required workflow recorded for review.');return render()}}
 if(b.dataset.add){if(reservationLocked()){toast('Reservation details are locked after proof submission. Start a new review to make changes.');return}const targetRoom=D.rooms.find(r=>r.id===b.dataset.add);if(!targetRoom||!availability(targetRoom).available){toast('This accommodation is unavailable for the selected dates. Choose different dates to continue.');return}if(!state.items.some(i=>i.resourceId===b.dataset.add)&&!iExclusive()){state.items.push(item(b.dataset.add));state.agreed=false;const name=D.rooms.find(r=>r.id===b.dataset.add).name;toast(`${name} added to booking.`);render();if($('#dialog').open&&gallery.room?.id===b.dataset.add)$('#dialogBody').innerHTML=galleryHTML()}return}
 if(b.hasAttribute('data-add-exclusive')){if(reservationLocked()){toast('Reservation details are locked after proof submission. Start a new review to make changes.');return}if(!state.items.length){state.items=[item(D.exclusive.id,'exclusive')];toast('Exclusive Resort Rental added.');render()}return}
 if(b.dataset.remove!=null){if(reservationLocked()){toast('Reservation details are locked after proof submission. Start a new review to make changes.');return}state.items.splice(Number(b.dataset.remove),1);state.agreed=false;toast('Stay removed from booking.');return render()}
 if(b.dataset.detail){return detailModal(D.rooms.find(r=>r.id===b.dataset.detail))}
 if(b.dataset.gallery){gallery.index=(gallery.index+Number(b.dataset.gallery)+gallery.room.images.length)%gallery.room.images.length;$('#dialogBody').innerHTML=galleryHTML();return}
 if(b.dataset.thumb!=null){gallery.index=Number(b.dataset.thumb);$('#dialogBody').innerHTML=galleryHTML()}
});
document.addEventListener('input',e=>{if(e.target.closest('#cartForm')){syncCart($('#cartForm'));refreshAllocation()}if(e.target.closest('#guestForm')||e.target.closest('#addonsForm'))captureDraft()});
document.addEventListener('change',e=>{if(e.target.name==='children'){const n=Math.max(0,Math.min(30,Number(e.target.value)||0));state.childAges=Array.from({length:n},(_,i)=>state.childAges[i]??'');$('#childAges').innerHTML=childAgeFields()}if(e.target.name==='checkIn'&&E.date(e.target.value)){const out=$('[name=checkOut]');out.min=E.addDay(e.target.value);if(out.value<=e.target.value)out.value=E.addDay(e.target.value)}if(e.target.closest('#cartForm')){syncCart($('#cartForm'));return render()}if(e.target.name==='method'&&e.target.closest('#paymentForm')){state.method=e.target.value;return render()}if(e.target.closest('#guestForm')||e.target.closest('#addonsForm'))captureDraft()});
document.addEventListener('submit',e=>{e.preventDefault();if(!e.target.reportValidity())return;const f=new FormData(e.target);
 if(e.target.id==='datesForm'){const a=f.get('checkIn'),b=f.get('checkOut'),n=E.nights(a,b),start=E.validateStayStart(a,new Date(),D.config);if(!start.valid)return errors([start.reason]);if(!E.date(b)||n<1)return errors(['Checkout must be after check-in.']);state.checkIn=a;state.checkOut=b;state.adults=Number(f.get('adults'));state.childAges=Array.from({length:Number(f.get('children'))},(_,i)=>f.get(`age-${i}`)===''?'':Number(f.get(`age-${i}`)));if(state.childAges.some(x=>x===''))return errors(['Select an age for every child.']);state.pets=f.has('pets');state.items=[];state.agreed=false;return setStep(1)}
 if(e.target.id==='cartForm'){syncCart(e.target);const a=allocation(),list=[];if(a.adultsLeft>0)list.push(`${a.adultsLeft} adult${a.adultsLeft===1?' is':'s are'} still unassigned.`);if(a.adultsLeft<0)list.push(`You have assigned ${a.assignedAdults} adults, but this reservation contains ${state.adults}.`);if(a.unassignedChildIndexes.length)list.push(`${a.unassignedChildIndexes.length} child${a.unassignedChildIndexes.length===1?' still needs':'ren still need'} an accommodation.`);if(a.duplicateChildIndexes.length)list.push('Each child may be assigned to exactly one accommodation.');list.push(...a.capacityErrors);list.push(...E.validation(state,D).filter(x=>!x.startsWith('Add at least')&&!/allows up to/.test(x)));if(list.length)return errors(list);state.agreed=false;return setStep(3)}
 if(e.target.id==='guestForm'){const mobile=String(f.get('mobile')).replace(/[\s()-]/g,'');if(!/^(09\d{9}|\+639\d{9}|639\d{9})$/.test(mobile))return errors(['Enter a valid Philippine mobile number beginning 09 or +639.']);const eta=String(f.get('eta')||''),etaMeta=E.etaWindow(state.checkIn,new Date(),D.config);if(!eta)return errors(['Choose an estimated arrival time.']);if(state.checkIn===today()&&eta<etaMeta.min)return errors([`For a same-day booking, estimated arrival cannot be earlier than ${etaMeta.min} PH time.`]);state.guest=Object.fromEntries(f);state.guest.mobile=mobile;state.agreed=false;return setStep(4)}
 if(e.target.id==='addonsForm'){state.requests=Object.fromEntries([...f].map(([k,v])=>[k,Number(v)]));state.agreed=false;return setStep(5)}
 if(e.target.id==='reviewForm'){state.agreed=f.has('agreed');if(!state.agreed)return errors(['Please agree to the booking, cancellation and rescheduling policies.']);return setStep(6)}
 if(e.target.id==='paymentForm'){const submit=$('#proofButton');if(state.busy||submit.disabled)return;const method=String(f.get('method')||'');if(!['gcash','bank'].includes(method))return errors(['Choose GCash or RCBC Bank Transfer.']);const proof=f.get('proof');if(!proof||!proof.name)return errors(['Choose a payment proof image.']);if(!['image/png','image/jpeg','image/webp'].includes(proof.type))return errors(['Payment proof must be a PNG, JPEG or WebP image.']);if(proof.size>10*1024*1024)return errors(['Payment proof must be 10 MB or smaller.']);state.busy=true;submit.disabled=true;submit.textContent='Submitting proof…';state.method=method;state.proof={name:proof.name,type:proof.type,size:proof.size};state.paymentStatus=E.transition(E.paymentTransitions,state.paymentStatus,'proof_submitted');state.paymentHistory.push(state.paymentStatus);state.bookingStatus=E.transition(E.bookingTransitions,state.bookingStatus,'submitted');state.bookingHistory.push(state.bookingStatus);state.paymentStatus=E.transition(E.paymentTransitions,state.paymentStatus,'verification_pending');state.paymentHistory.push(state.paymentStatus);state.bookingStatus=E.transition(E.bookingTransitions,state.bookingStatus,'pending_payment_verification');state.bookingHistory.push(state.bookingStatus);state.reference='SWR-REVIEW-'+Math.random().toString(36).slice(2,8).toUpperCase();state.busy=false;return setStep(7)}
});
$('#mobileCart').addEventListener('click',()=>{if(reservationLocked())return toast('Reservation details are locked after payment proof submission. Start a new review to make changes.');setStep(2)});$('#policyButton').addEventListener('click',()=>{$('#dialogBody').innerHTML=`<h2 id="dialogTitle">Booking policies</h2>${policies()}`;$('#dialog').showModal()});$('#dialog .dialog-close').addEventListener('click',()=>$('#dialog').close());$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog'))$('#dialog').close()});
render();
